MLproject: MLproject
supported_target: azureml,mlflow
project_type: train_your_own_model
conda_env: conda.yml
deploy_config: .metadata/deploy/deploy_config.yml
code:
  deployment: 'src/luna/deploy.py'
  score: 'src/luna/score.py'
  training: 'src/luna/train.py'
  batchinference: 'src/luna/batchinference.py'
azureml:
  run_config: .cloud/.azureml/aml_run_config.yml
  workspace_config: .cloud/.azureml/workspace.yml
  default_workspace: .cloud/.azureml/default_workspace.json
mlflow:
  spark_config: .cloud/.mlflow/spark_config.json
  workspace_config: .cloud/.mlflow/workspace.yml